AWSTemplateFormatVersion: 2010-09-09

Resources:
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: luke-hackett-static-website
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  WebsiteBucketBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    DependsOn: WebsiteBucket
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: 'Website CloudFront Distribution'
        DefaultRootObject: 'index.html'
        PriceClass: 'PriceClass_100'
        Origins:
          - Id: !Sub '${WebsiteBucket}.s3.${AWS::Region}.amazonaws.com'
            DomainName: !Sub '${WebsiteBucket}.s3.${AWS::Region}.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentity}'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'GET'
            - 'HEAD'
            - 'OPTIONS'
          DefaultTTL: 3600
          ForwardedValues:
            QueryString: 'true'
            Cookies:
              Forward: 'none'
          TargetOriginId: !Sub '${WebsiteBucket}.s3.${AWS::Region}.amazonaws.com'
          ViewerProtocolPolicy: 'https-only'
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 403
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 30
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: '/error.html'
            ErrorCachingMinTTL: 30
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
  
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub '${WebsiteBucket} OAI'

Outputs:
  WebsiteURL:
    Description: HTTPS Cloudfront URL for the S3 hosted website
    Value: !Sub 'https://${CloudFrontDistribution.DomainName}'
  WebsiteBucket:
    Description: S3 URL for the S3 hosted website
    Value: !Sub 's3://${WebsiteBucket}'
